#!/bin/bash
# run_emu.sh — benchmark all 7 kernels under the PTX emulator (16 KB input)
#
# Usage:
#   bash run_emu.sh [--cuemu /path/to/build]
#
# Defaults: CUEMU_BUILD = ../build  (relative to this script)
#
# Output:
#   results/emu_results.csv    — raw CSV
#   results/emu_table.tex      — LaTeX table fragment

set -euo pipefail
export LC_ALL=C
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$SCRIPT_DIR/src"
BIN="$SCRIPT_DIR/bin"
RES="$SCRIPT_DIR/results"
mkdir -p "$BIN" "$RES"

# ── locate emulator ───────────────────────────────────────────────────────────
CUEMU_BUILD="${CUEMU_BUILD:-$SCRIPT_DIR/../build}"
if [[ "${1:-}" == "--cuemu" ]]; then CUEMU_BUILD="${2:?'path required'}"; shift 2; fi

LIBEMURUNTIME="$CUEMU_BUILD/lib/libemuruntime.so"
if [[ ! -f "$LIBEMURUNTIME" ]]; then
    echo "ERROR: libemuruntime.so not found at $LIBEMURUNTIME" >&2
    echo "  Set CUEMU_BUILD or pass --cuemu /path/to/build" >&2
    exit 1
fi
echo "Emulator: $LIBEMURUNTIME"

# ── compile (same arch as emulator test suite: sm_75) ────────────────────────
NVCC_FLAGS="-O2 -arch=sm_75 --cudart=shared -lineinfo"
echo "Compiling..."
for f in vadd gelu softmax mmul attention fft cg; do
    nvcc $NVCC_FLAGS "$SRC/${f}_bench.cu" -o "$BIN/${f}_bench" 2>/dev/null
    echo "  ${f}_bench OK"
done

# ── emulator runner ───────────────────────────────────────────────────────────
emu_run() {
    local BIN_PATH=$1 PROF=$2
    LC_ALL=C \
    CUEMU_COLLECT_PROFILING=$PROF \
    CUEMU_PROFILING_OUTPUT=/dev/null \
    CUEMU_TARGET_EXEC="$BIN_PATH" \
    LD_PRELOAD="$LIBEMURUNTIME" \
    LD_LIBRARY_PATH="$CUEMU_BUILD/lib:${LD_LIBRARY_PATH:-}" \
    "$BIN_PATH" 2>/dev/null
}

# ── metadata ──────────────────────────────────────────────────────────────────
declare -A FLOPS=( [vadd]=16384      [gelu]=163840   [softmax]=49152
                   [mmul]=4194304   [attention]=8437760
                   [fft]=204800     [cg]=696320 )
declare -A BYTES=( [vadd]=98304     [gelu]=131072   [softmax]=131072
                   [mmul]=196608    [attention]=327680
                   [fft]=131072     [cg]=1474560 )
declare -A SIZES=( [vadd]="N=8192"  [gelu]="N=16384"      [softmax]="512×32"
                   [mmul]="128×128" [attention]="S=D=128"
                   [fft]="N=32,B=256" [cg]="N=4096,it=10" )

# ── run all kernels ───────────────────────────────────────────────────────────
echo ""
echo "Running without profiling..."
CSV="$RES/emu_results.csv"
echo "kernel,size,time_no_prof_ms,time_with_prof_ms,overhead_pct,flops,bytes,ai" > "$CSV"

declare -A T_NO T_WP
for f in vadd gelu softmax mmul attention fft cg; do
    printf "  %-12s no-prof ... " "$f"
    T_NO[$f]=$(emu_run "$BIN/${f}_bench" 0)
    printf "%.4f ms\n" "${T_NO[$f]}"
done

echo ""
echo "Running with profiling..."
for f in vadd gelu softmax mmul attention fft cg; do
    printf "  %-12s with-prof ... " "$f"
    T_WP[$f]=$(emu_run "$BIN/${f}_bench" 1)
    printf "%.4f ms\n" "${T_WP[$f]}"

    NO=${T_NO[$f]}; WP=${T_WP[$f]}
    F=${FLOPS[$f]}; B=${BYTES[$f]}
    PCT=$(python3 -c "print(f'{($WP-$NO)/$NO*100:.1f}')")
    AI=$(python3 -c "print(f'{$F/$B:.3f}')")
    echo "$f,\"${SIZES[$f]}\",$NO,$WP,$PCT,$F,$B,$AI" >> "$CSV"
done

# ── produce LaTeX table ───────────────────────────────────────────────────────
TEX="$RES/emu_table.tex"
cat > "$TEX" << 'TEXEOF'
% Emulator benchmark results — generated by run_emu.sh
% Paste into ch8_testing.tex, replaces or extends tab:integration_results
\begin{table}[h]
  \caption{Производительность эмулятора на 16~КБ входных данных
           (медиана повторных запусков в одном процессе).
           Overhead~--- замедление от включения сбора профилировочных данных.}
  \label{tab:emu_bench_16k}
  \centering
  \footnotesize
TEXEOF

echo "  \\begin{tabular}{lrrrr}" >> "$TEX"
echo "    \\toprule" >> "$TEX"
printf "    %-30s & %-10s & %-10s & %-8s & %-8s \\\\\\\\\n" \
    "\\textbf{Ядро (размер)}" \
    "\\textbf{Без проф.}" "\\textbf{Со сбором}" \
    "\\textbf{OH, \\%}" "\\textbf{AI}" >> "$TEX"
printf "    %-30s & %-10s & %-10s & %-8s & %-8s \\\\\\\\\n" \
    "" "(мс)" "(мс)" "" "(Ф/Б)" >> "$TEX"
echo "    \\midrule" >> "$TEX"

python3 - "$CSV" << 'PYEOF' >> "$TEX"
import csv, sys
labels = {'vadd':r'\texttt{vadd}','gelu':r'\texttt{gelu}',
          'softmax':r'\texttt{softmax}','mmul':r'\texttt{mmul}',
          'attention':r'\texttt{attention}','fft':r'\texttt{fft}',
          'cg':r'\texttt{conj\_grad}'}
with open(sys.argv[1]) as f:
    for r in csv.DictReader(f):
        k  = r['kernel']
        sz = r['size'].strip('"')
        no = float(r['time_no_prof_ms'])
        wp = float(r['time_with_prof_ms'])
        oh = float(r['overhead_pct'])
        ai = float(r['ai'])
        name = f"{labels.get(k,k)} ({sz})"
        print(f"    {name:<38} & {no:>8.1f} & {wp:>8.1f} & {oh:>6.0f} & {ai:>6.3f} \\\\")
PYEOF

cat >> "$TEX" << 'TEXEOF'
    \bottomrule
  \end{tabular}
\end{table}
TEXEOF

# ── summary ───────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════════"
printf "%-14s | %10s | %11s | %7s | %6s\n" \
    "Kernel" "No-prof ms" "With-prof ms" "OH %" "AI"
echo "────────────────────────────────────────────────────────────────"
python3 - "$CSV" << 'PYEOF'
import csv, sys
with open(sys.argv[1]) as f:
    for r in csv.DictReader(f):
        print(f"{r['kernel']:<14} | {float(r['time_no_prof_ms']):>10.2f} | "
              f"{float(r['time_with_prof_ms']):>11.2f} | "
              f"{float(r['overhead_pct']):>7.1f} | "
              f"{float(r['ai']):>6.3f}")
PYEOF
echo "════════════════════════════════════════════════════════════════"
echo "CSV  → $CSV"
echo "LaTeX→ $TEX"
